### ISSUE TITLE
TypeScript definition

### ISSUE THREAD

**Issue by patarapolw** [jkroso/parse-duration#12]
According to <https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html>, this is as simple as

```typescript
// ./index.d.ts

export = parse

/**
 * convert `str` to ms
 */
function parse (str: string): number
```

And, add `"typings": "index.d.ts"`, in your `package.json`. Then, upload to NPM.

Might create a Pull Request later. Hope this package will be actively maintained.

Anyways, for anyone reading this, you can also create `declaration.d.ts` with

```typescript
declare module 'parse-duration' {
  export = parse

  /**
   * convert `str` to ms
   */
  function parse (str: string): number
}
```

**Comment by rikkegammelmark** [comment]
Any news on this? It would be great to be able to use this with typescript.

**Comment by dy** [comment]
Fixed
