### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by liorfr** [jkroso/parse-duration#19]
Please see TS project:
https://codesandbox.io/s/misty-framework-1u19b?file=/src/index.ts

It can be solved by adding
"esModuleInterop": true
To the tsconfig.json but a namespace solution is a bad practice

Thanks
Lior

**Comment by dy** [comment]
> namespace solution is a bad practice
Can you give reference? This problem seems to be out of current package scope, it is perfectly fine in node and with browserify. ESM entry is going to be a separate release.

**Comment by dy** [comment]
Ok, added ESM entry. Try v0.4.0
