### ISSUE TITLE
same error with 0.4.2

### ISSUE THREAD

**Issue by liorfr** [jkroso/parse-duration#21]
Hi,

I ran the example with 0.4.2 and got the same error
https://codesandbox.io/s/misty-framework-1u19b?file=/src/index.ts

Thanks
Lior

**Comment by dy** [comment]
You include `index.ts` file - if you rename it to `.js` it simply works.
https://codesandbox.io/s/sleepy-tereshkova-nr7bb
The module is compatible with ESM and works as expected in node, browser and by standard.
If you find out how to make typescript work - PR welcome.

**Comment by dy** [comment]
Try 0.4.4

**Comment by liorfr** [comment]
@dy, working as expected now :)

**Comment by liorfr** [comment]
Thanks !

**Comment by dy** [comment]
Thanks to @alonesuperman

**Comment by liorfr** [comment]
@alonesuperman, just out of curiosity (I did not find an answer online) can you please explain how module.exports.default solves the commonjs module es module issue ?
What happens behind the scenes when I try to import this default module in TypeScript ?

**Comment by alonesuperman** [comment]
> @alonesuperman, just out of curiosity (I did not find an answer online) can you please explain how module.exports.default solves the commonjs module es module issue ?
> What happens behind the scenes when I try to import this default module in TypeScript ?

#23 maybe was helpful

And https://stackoverflow.com/questions/29596714/new-es6-syntax-for-importing-commonjs-amd-modules-i-e-import-foo-require
show the reason

**Comment by liorfr** [comment]
@alonesuperman, Thanks !!
