### ISSUE TITLE
Add module.exports.default or refactor d.ts file 

### ISSUE THREAD

**Issue by alonesuperman** [jkroso/parse-duration#23]
As we known, the dist file was commonjs styled, but d.ts use ESM to describe it.

### my tsconfig
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "strict": true,
    "noImplicitAny": true,
    "incremental": true,
    "resolveJsonModule": true,
    "types": [
      "node",
      "jest"
    ],
    "lib": [
      "ESNext",
      "ScriptHost",
    ]
  },
  "exclude": ["node_modules", "dist"]
}
```

### source code in .ts file
```typescript
import parse from "parse-duration";

parse("30 mins");
```
### target (compiled by tsc)  in .js file
```javascript
const parse_duration_1 = tslib_1.__importDefault(require("parse-duration"));
parse_duration_1.default("30 mins");
```
Above code should have runtime error certainly

So we have to use `esModuleInterop` (maybe some other option needed?)

# My Suggestion1 (Not Recommand)
Is it necessary？ I think if u can modify the d.ts file

https://github.com/jkroso/parse-duration/blob/527da68d441b0174069c3f6c3ea4ba5da14b494f/index.d.ts#L18

 to below code, we can drop `esModuleInterop` option

```typescript
// ...Units defintion
declare function parse (str: string, format?: Units): number | null
export = parse
```
then we can easily use `import parse = require("parse-duration")`

# My suggestion2 (Recommand)

forget suggestion1 then just simple add `module.exports.default =  parse` in your index.js

**Comment by dy** [comment]
Ok, I'm more inclined towards 1.

Changing standard JS code just to make it compatible with TypeScript (it has opinionated idea on how import/export should look) does not seem to correspond to package's purpose.

I'd prefer to have type definitions moved out to npm.com/@types/parse-duration (that was deprecated recently), and manage definitions and related issues there.

**Comment by dy** [comment]
Not to spend time on it, I'll merge the PR.

**Comment by alonesuperman** [comment]
> Ok, I'm more inclined towards 1.
> 
> Changing standard JS code just to make it compatible with TypeScript (it has opinionated idea on how import/export should look) does not seem to correspond to package's purpose.
> 
> I'd prefer to have type definitions moved out to npm.com/@types/parse-duration (that was deprecated recently), and manage definitions and related issues there.

The reason for `suggestion 2` was I had seen some popular lib do the same thing, e.g axios😄

**Comment by dy** [comment]
I just don't want to troubleshoot typescript related issues anymore, wasted enough time on it already instead of doing actual coding. If you want to take that part - you're welcome.
