### ISSUE TITLE
[feature request] support more units which not in English

### ISSUE THREAD

**Issue by alonesuperman** [jkroso/parse-duration#26]
Hi,  jkroso

Although we can use `parse.newUnit` to extend more unit, your regexp may limit the unit as [a-zµμ]

I suggest it could change to some else such as [^\d\s] to make more possibility

The change is just example, It fail to pass test case because of the noisy word

So  a safer way could be either of follow:

- Check the last capture group
    1.  Give the parse object a method called registerUnit, it will push all unit into an array
    2. The last capture group (unit) will check if it contains any unit

- Dynamically create regular expressions by current units collection array

If u agree, I can do some job(by the way, improve the .d.ts file to allow us extend units under typescript) and take a pr in several days

**Comment by dy** [comment]
No need for dynamic rules/units, locales can be added separately.

**Comment by alonesuperman** [comment]
wu..., but how to add locale without refactor?

**Comment by dy** [comment]
@alonesuperman something like 
```js
import parse from 'parse-duration'
parse['сек'] = parse['s'] // ru seconds
parse('5сек') // 5000
```
should be enough.
If you wish to come up with a PR, adding locales as
```js
import parse from 'parse-duration'
import 'parse-duration/fr'
```
you're welcome

**Comment by alonesuperman** [comment]
No, I had run test case for some times

If u use 0.4.4 without any change(except test case), let us see the test case below

![image](https://user-images.githubusercontent.com/21165139/88126509-3d622880-cc04-11ea-8362-04baf4820a08.png)

**Comment by alonesuperman** [comment]
And, If u apply my suggestion about modify regexp still can not pass the test case for this three`running length: 1hour:20mins`, `1y.2b.5days.12hours.34sec.20ms`, `-1y.2b.5days 12hours,34sec,20ms`

**Comment by dy** [comment]
Right, it needs adjusting regex to match [unicode property escapes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes)
like that `var duration = /(-?(?:\d+\.?\d*|\d*\.?\d+)(?:e[-+]?\d+)?)\s*([\p{L}]*)/uig`
I can't contribute for some time, so if you'd like PR welcome!

**Comment by alonesuperman** [comment]
OK, Let me have a try

**Comment by dy** [comment]
Added unicode support in v1.0
