### ISSUE TITLE
[feature request] Support for verbose number representation

### ISSUE THREAD

**Issue by jay-khatri** [jkroso/parse-duration#27]
Hi, any thoughts on supporting spelled out numbers. E.g. "one hour" and "twenty four days"?

**Comment by dy** [comment]
Hey. Definitely not, parsing written numbers is the concern outside of this
package. I’d propose parsing/replacing spelled numbers first with some tool
and then feeding them here.

**Comment by jay-khatri** [comment]
sounds good 🆗 👌
