### ISSUE TITLE
Two minor but rather non-expected cases of behaviour

### ISSUE THREAD

**Issue by hrbaer** [jkroso/parse-duration#28]
Dear Jake

Thanks for your code. I would like to inform you on two cases I recently encountered:

```javascript
let n = parse(1)
```

`index.js:62
 str = str.replace(/(\d),(\d)/g, '$1$2')
            ^
TypeError: str.replace is not a function`

```javascript
let n = parse('1')   // => null
```

In both cases I would rather expect a returned value of 1.

Regards
H. R. Baer

**Comment by dy** [comment]
Makes sense. v0.5.0 defaults unitless numbers to ms.
Cheers.
