### ISSUE TITLE
Integrate into compute-incrdatespace

### ISSUE THREAD

**Issue by dy** [jkroso/parse-duration#7]
Here is awesome package using the same functionality: https://github.com/compute-io/incrdatespace

I think it would be winning for both to cross-test cases and make integration.

The cases:

* ms, millisecond, milliseconds
* s, sec, secs, second, seconds
* m, min, mins, minute, minutes
* h, hr, hrs, hour, hours
* d, day, days
* w, wk, wks, week, weeks
* b, month, months
* y, yr, yrs, year, years

Anyways there is no tests, so mb worth adding.
Just for note.

cc @kgryte is there any sense in that?

**Comment by jkroso** [comment]
The Readme used to be runnable and served as the test suite. Not sure if that still works. Anyway feel free to add tests!

**Comment by dy** [comment]
Closed.
